ci: Build static monaco binary
dynatrace-oss/dynatrace-monitoring-as-code pull request #579
Opened 2022-03-19 16:13 UTC by patrickpichler

In order to be libc agnostic, monaco is now build as a static binary.

fix #567

2022-06-10 12:20 UTC, UnseenWizzard commented
released binaries are actually still built with xgo in https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/main/.github/workflows/release.yml#L31 and do not use the build cmd from the Makefile...

As that isn't actually needed for cross compiling since go 1.15 and xgo is archived the release built should be changed to just build using different OS/ARCH vars... 
As a quick solution for this the same tags and ld_flags could be passed to xgo as well though

2022-06-13 05:49 UTC, patrickpichler commented
I have dropped `xgo` from the release action and updated the `make build` goal to cross compile to all supported architectures.

2022-07-19 09:40 UTC, UnseenWizzard requested changes

2022-07-27 11:46 UTC, UnseenWizzard commented on Makefile
> +	GOOS=windows GOARCH=386 CGO_ENABLED=0 go build -tags netgo -ldflags '-w -extldflags "-static"' -o ./bin/${EXECUTABLE}-windows-386.exe ./cmd/monaco
the release build will miss these as it's uploading assets from a `build` folder, not `bin`, pls adapt one of them

2022-07-27 12:58 UTC, Laubi commented
This PR also fixes #702

2022-07-27 13:09 UTC, merged